name: install-concordia

inputs:
  python-version:
    description: Python version
    required: false
    default: '3.11'
    type: string

runs:
  using: composite
  steps:
    - name: Get current runner
      id: os-info
      shell: bash
      run: |
        if [ "${RUNNER_OS}" = 'macOS' ]; then
          echo "name=$(sw_vers -productName)" >> $GITHUB_OUTPUT
          echo "version=$(sw_vers -productVersion)" >> $GITHUB_OUTPUT
        elif [ "${RUNNER_OS}" = 'Linux' ]; then
          echo "name=$(lsb_release -i -s)" >> $GITHUB_OUTPUT
          echo "version=$(lsb_release -r -s)" >> $GITHUB_OUTPUT
        else
          exit 1
        fi

    - name: Set up Python ${{ inputs.python-version }}
      id: setup-python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
      with:
        python-version: ${{ inputs.python-version }}

    - name: Restore Concordia installation
      id: restore
      uses: actions/cache/restore@ab5e6d0c87105b4c9c2047343972218f562e4319
      with:
        path: venv
        key: install-concordia-${{ steps.os-info.outputs.name }}-${{ steps.os-info.outputs.version }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          install-concordia-${{ steps.os-info.outputs.name }}-${{ steps.os-info.outputs.version }}-py${{ steps.setup-python.outputs.python-version }}-

    - name: Install Concordia
      if: steps.restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --editable .[dev]

    - name: Save Concordia installation
      if: steps.restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@ab5e6d0c87105b4c9c2047343972218f562e4319
      with:
        path: venv
        key: ${{ steps.restore.outputs.cache-primary-key }}

    - name: Activate virtual environment
      shell: bash
      run: |
        source venv/bin/activate
        pip list
        echo "PATH=${PATH}" >> $GITHUB_ENV
