name: pytype-examples

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/pytype-examples.yml'
      - 'examples/**'
      - 'concordia/**'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/pytype-examples.yml'
      - 'examples/**'
      - 'concordia/**'
      - 'pyproject.toml'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pytype:
    name: Typecheck examples
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Concordia
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Install examples
        uses: ./.github/actions/install-examples

      - name: Run PyType on examples
        run: pytype examples

      - name: Run PyType on notebooks
        run: pytype --pythonpath=. notebooks
